version: '3.3'
services:
  asterisk:
    image: ghostdial/asterisk
    build:
      context: ./services/asterisk
      dockerfile: Dockerfile
    ports:
      - 35061:35061/tcp
    environment:
      - ASTERISK_UID=1010
      - ASTERISK_GID=7087
      - EXTERNIP=${EXTERNIP}
      - VOIPMS_SIP_USERNAME=${VOIPMS_SIP_USERNAME}
      - VOIPMS_SIP_PASSWORD=${VOIPMS_SIP_PASSWORD}
      - VOIPMS_SIP_PROTOCOL=${VOIPMS_SIP_PROTOCOL}
      - VOIPMS_SIP_HOST=${VOIPMS_SIP_HOST}
      - VOIPMS_SIP_PORT=${VOIPMS_SIP_PORT}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - REDIS_URI=redis://redis:6379
      - DOMAIN=${DOMAIN}
      - CERTS_GID=7077
    volumes:
      - letsencrypt:/etc/letsencrypt
      - asterisk:/etc/asterisk
      - spool:/var/spool
      - logs:/var/log
    depends_on:
      - redis
    restart: unless-stopped
  fail2ban:
    image: ghostdial/fail2ban
    build:
      context: ./services/fail2ban
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: 'host'
    environment:
      - PUID=1000
      - PGID=7077
      - TZ=Etc/UTC
      - VERBOSITY=-vv
    volumes:
      - logs:/var/log
    restart: unless-stopped
  prosody:
    image: ghostdial/prosody
    build:
      context: ./services/prosody
      dockerfile: Dockerfile
    ports:
      - 5222:5222
      - 5223:5223
      - 5269:5269
      - 5347:5347
      - 5280:5280
      - 5281:5281
    environment:
      - CERTS_GID=7077
      - REDIS_URI=redis://redis:6379
      - DOMAIN=${DOMAIN}
      - ROOT_PASSWORD=${ROOT_PASSWORD}
    volumes:
      - letsencrypt:/etc/letsencrypt
      - logs:/usr/local/var/log
      - prosody:/usr/local/var/lib/prosody
    depends_on:
      - redis
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    ports:
      - 80:80/tcp
    command: ["certonly", "--standalone", "--email", "${EMAIL}", "-d", "${DOMAIN}", "--agree-tos", "--no-eff-email"]
    environment:
      - CERTS_GID=7077
    volumes:
      - letsencrypt:/etc/letsencrypt
  redis:
    image: redis
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis:/data
    restart: unless-stopped
  sms_pipeline:
    image: ghostdial/sms_pipeline
    build:
      context: ./
      dockerfile: Dockerfile-sms
    volumes:
      - sms_pipeline:/data
    environment:
      - VOIPMS_USERNAME=${VOIPMS_API_USERNAME}
      - VOIPMS_PASSWORD=${VOIPMS_API_PASSWORD}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - GHOST_NUMBER=8008888080
      - SMS_SQLITE3_DATABASE=/data/sms.db
      - REDIS_URI=redis://redis:6379
    restart: unless-stopped
  dossi:
    image: ghostdial/sms_pipeline
    build:
      context: ./
      dockerfile: Dockerfile-dossi
    environment:
      - DOMAIN=${DOMAIN}
      - REDIS_URI=redis://redis:6379
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - ROOT_PASSWORD=${ROOT_PASSWORD}
    restart: unless-stopped
  voicemail_pipeline:
    image: ghostdial/voicemail_pipeline
    build:
      context: ./
      dockerfile: Dockerfile-voicemail
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/gcloud/serviceaccount.json
      - DOMAIN=${DOMAIN}
      - ROOT_PASSWORD=${ROOT_PASSWORD}
    volumes:
      - asterisk:/etc/asterisk
      - spool:/var/spool
      - gcloud:/gcloud
      - prosody:/var/lib/prosody
    restart: unless-stopped
volumes:
  redis:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GHOSTDIAL_DATABASE}/redis
  letsencrypt:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GHOSTDIAL_DATABASE}/letsencrypt
  asterisk:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GHOSTDIAL_DATABASE}/asterisk
  spool:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GHOSTDIAL_DATABASE}/spool
  prosody:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GHOSTDIAL_DATABASE}/prosody
  gcloud:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GHOSTDIAL_DATABASE}/gcloud
  sms_pipeline:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GHOSTDIAL_DATABASE}/sms_pipeline
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GHOSTDIAL_DATABASE}/logs
